// SUBREDDIT QUALITY TIERS - Higher tier = better quality leads
const subredditTiers = {
  premium: {
    multiplier: 1.4,
    subreddits: [
      "entrepreneur",
      "startups",
      "entrepeneurridealong",
      "indiehackers",
      "smallbusiness",
      "saas",
      "marketing",
      "growmybusiness",
      "startupbiz",
    ],
  },
  quality: {
    multiplier: 1.2,
    subreddits: [
      "uxdesign",
      "userexperience",
      "web_design",
      "design_critiques",
      "sideproject",
      "cofounder",
      "askmarketing",
    ],
  },
  standard: {
    multiplier: 1.0,
    subreddits: ["freelancedesign", "designjobs", "webdev", "business"],
  },
  lowQuality: {
    multiplier: 0.7,
    subreddits: [
      "forhire",
      "slavelabour",
      "jobs",
      "hireawriter",
      "designjobs",
      "freelance_forhire",
    ],
  },
};

// EXCLUSION PATTERNS - Posts matching these get filtered out
const exclusionPatterns = {
  students: [
    { phrase: "student project", weight: 100 },
    { phrase: "university assignment", weight: 100 },
    { phrase: "college project", weight: 100 },
    { phrase: "school assignment", weight: 100 },
    { phrase: "homework help", weight: 100 },
    { phrase: "thesis project", weight: 100 },
    { phrase: "capstone project", weight: 80 },
    { phrase: "class project", weight: 100 },
    { phrase: "academic project", weight: 90 },
    { phrase: "learning project", weight: 70 },
    { phrase: "practice project", weight: 60 },
    { phrase: "first time doing", weight: 50 },
    { phrase: "beginner project", weight: 60 },
  ],
  jobOffers: [
    { phrase: "we are hiring", weight: 100 },
    { phrase: "job opening", weight: 100 },
    { phrase: "position available", weight: 100 },
    { phrase: "join our team", weight: 100 },
    { phrase: "career opportunity", weight: 100 },
    { phrase: "full time position", weight: 100 },
    { phrase: "part time position", weight: 100 },
    { phrase: "remote position", weight: 80 },
    { phrase: "job posting", weight: 100 },
    { phrase: "apply now", weight: 90 },
    { phrase: "send resume", weight: 100 },
    { phrase: "send cv", weight: 100 },
  ],
  bigCorporations: [
    { phrase: "fortune 500", weight: 100 },
    { phrase: "enterprise company", weight: 90 },
    { phrase: "multinational", weight: 80 },
    { phrase: "1000+ employees", weight: 100 },
    { phrase: "500+ employees", weight: 90 },
    { phrase: "corporate team", weight: 70 },
    { phrase: "large corporation", weight: 85 },
    { phrase: "big company", weight: 60 },
    { phrase: "established company", weight: 50 },
    { phrase: "public company", weight: 70 },
  ],
  personalProjects: [
    { phrase: "personal project", weight: 80 },
    { phrase: "hobby project", weight: 90 },
    { phrase: "side hobby", weight: 80 },
    { phrase: "just for fun", weight: 100 },
    { phrase: "no budget", weight: 100 },
    { phrase: "free work", weight: 100 },
    { phrase: "volunteer project", weight: 90 },
    { phrase: "non profit", weight: 60 },
    { phrase: "charity project", weight: 70 },
    { phrase: "family business", weight: 40 },
    { phrase: "friends project", weight: 80 },
  ],
  internships: [
    { phrase: "internship", weight: 100 },
    { phrase: "intern position", weight: 100 },
    { phrase: "unpaid position", weight: 100 },
    { phrase: "work experience", weight: 70 },
    { phrase: "entry level", weight: 50 },
    { phrase: "junior position", weight: 40 },
  ],
  established: [
    { phrase: "been in business for", weight: 60 },
    { phrase: "established brand", weight: 70 },
    { phrase: "10+ years", weight: 80 },
    { phrase: "mature company", weight: 75 },
    { phrase: "legacy brand", weight: 80 },
  ],
};

// Signal patterns for analysis
const signalPatterns = {
  hire: {
    direct: [
      { phrase: "looking to hire", weight: 30 },
      { phrase: "hiring", weight: 25 },
      { phrase: "need a designer", weight: 35 },
      { phrase: "need developer", weight: 35 },
      { phrase: "freelancer needed", weight: 30 },
      { phrase: "contractor wanted", weight: 28 },
      { phrase: "looking for someone", weight: 20 },
      { phrase: "seeking designer", weight: 32 },
      { phrase: "recruiting", weight: 25 },
      { phrase: "talent acquisition", weight: 22 },
    ],
    indirect: [
      { phrase: "recommendations for", weight: 15 },
      { phrase: "who can help", weight: 18 },
      { phrase: "looking for help", weight: 16 },
      { phrase: "need someone", weight: 20 },
      { phrase: "where to find", weight: 12 },
      { phrase: "suggestions for", weight: 14 },
      { phrase: "anyone know", weight: 10 },
      { phrase: "point me towards", weight: 12 },
    ],
    project: [
      { phrase: "working on", weight: 8 },
      { phrase: "building", weight: 12 },
      { phrase: "creating", weight: 10 },
      { phrase: "developing", weight: 14 },
      { phrase: "starting", weight: 16 },
      { phrase: "launching", weight: 18 },
    ],
    pain: [
      { phrase: "struggling with", weight: 25 },
      { phrase: "having trouble", weight: 22 },
      { phrase: "need help with", weight: 20 },
      { phrase: "stuck on", weight: 24 },
      { phrase: "frustrated with", weight: 26 },
      { phrase: "can't figure out", weight: 20 },
    ],
  },
  budget: {
    explicit: [
      { phrase: "$", weight: 25 },
      { phrase: "€", weight: 25 },
      { phrase: "£", weight: 25 },
      { phrase: "budget", weight: 30 },
      { phrase: "pay", weight: 20 },
      { phrase: "cost", weight: 15 },
      { phrase: "price", weight: 18 },
      { phrase: "rate", weight: 22 },
      { phrase: "salary", weight: 28 },
      { phrase: "fee", weight: 20 },
      { phrase: "compensation", weight: 25 },
    ],
    range: [
      { phrase: "k", weight: 20 },
      { phrase: "000", weight: 18 },
      { phrase: "thousand", weight: 22 },
      { phrase: "per hour", weight: 25 },
      { phrase: "/hr", weight: 25 },
      { phrase: "hourly", weight: 24 },
      { phrase: "fixed price", weight: 20 },
      { phrase: "project basis", weight: 18 },
      { phrase: "retainer", weight: 26 },
    ],
    context: [
      { phrase: "investment", weight: 22 },
      { phrase: "funding", weight: 24 },
      { phrase: "afford", weight: 18 },
      { phrase: "spend", weight: 16 },
      { phrase: "allocated", weight: 20 },
      { phrase: "approved budget", weight: 30 },
      { phrase: "financial backing", weight: 25 },
    ],
    signals: [
      { phrase: "serious about", weight: 15 },
      { phrase: "ready to invest", weight: 25 },
      { phrase: "quality work", weight: 12 },
      { phrase: "professional", weight: 10 },
      { phrase: "not looking for cheap", weight: 20 },
    ],
  },
  urgent: {
    immediate: [
      { phrase: "asap", weight: 30 },
      { phrase: "urgent", weight: 28 },
      { phrase: "immediately", weight: 32 },
      { phrase: "right now", weight: 30 },
      { phrase: "emergency", weight: 35 },
      { phrase: "rush", weight: 25 },
      { phrase: "quickly", weight: 20 },
    ],
    timebound: [
      { phrase: "deadline", weight: 25 },
      { phrase: "by friday", weight: 28 },
      { phrase: "this week", weight: 26 },
      { phrase: "next week", weight: 24 },
      { phrase: "launch date", weight: 22 },
      { phrase: "timeline", weight: 20 },
      { phrase: "schedule", weight: 18 },
      { phrase: "time sensitive", weight: 24 },
    ],
    pressure: [
      { phrase: "behind schedule", weight: 26 },
      { phrase: "need fast", weight: 22 },
      { phrase: "quick turnaround", weight: 24 },
      { phrase: "running out of time", weight: 28 },
    ],
  },
  decision: {
    authority: [
      { phrase: "i am the", weight: 25 },
      { phrase: "ceo", weight: 30 },
      { phrase: "founder", weight: 28 },
      { phrase: "owner", weight: 26 },
      { phrase: "decision maker", weight: 30 },
      { phrase: "co-founder", weight: 28 },
      { phrase: "startup founder", weight: 32 },
      { phrase: "business owner", weight: 25 },
    ],
    responsibility: [
      { phrase: "my company", weight: 20 },
      { phrase: "our startup", weight: 22 },
      { phrase: "i need", weight: 15 },
      { phrase: "we need", weight: 12 },
      { phrase: "my business", weight: 18 },
      { phrase: "our team", weight: 14 },
    ],
    ownership: [
      { phrase: "my project", weight: 16 },
      { phrase: "working on my", weight: 14 },
      { phrase: "building my", weight: 16 },
      { phrase: "starting my", weight: 18 },
    ],
  },
  strategic: {
    scaling: [
      { phrase: "scaling", weight: 22 },
      { phrase: "growth", weight: 18 },
      { phrase: "expand", weight: 20 },
      { phrase: "growing fast", weight: 24 },
      { phrase: "scale up", weight: 22 },
      { phrase: "next level", weight: 20 },
    ],
    pivoting: [
      { phrase: "pivot", weight: 25 },
      { phrase: "change direction", weight: 22 },
      { phrase: "new strategy", weight: 20 },
      { phrase: "rebranding", weight: 24 },
      { phrase: "repositioning", weight: 22 },
    ],
    launching: [
      { phrase: "launch", weight: 20 },
      { phrase: "go to market", weight: 25 },
      { phrase: "pre-launch", weight: 22 },
      { phrase: "beta", weight: 15 },
      { phrase: "mvp", weight: 18 },
      { phrase: "minimum viable", weight: 16 },
    ],
    improving: [
      { phrase: "redesign", weight: 18 },
      { phrase: "refresh", weight: 15 },
      { phrase: "update", weight: 12 },
      { phrase: "modernize", weight: 16 },
      { phrase: "improve", weight: 14 },
      { phrase: "enhance", weight: 16 },
    ],
  },
  competitor: {
    dissatisfaction: [
      { phrase: "disappointed with", weight: 25 },
      { phrase: "bad experience", weight: 28 },
      { phrase: "terrible service", weight: 30 },
      { phrase: "unhappy with", weight: 24 },
      { phrase: "looking for alternative", weight: 26 },
      { phrase: "fed up with", weight: 28 },
    ],
    comparison: [
      { phrase: "better than", weight: 18 },
      { phrase: "alternative to", weight: 20 },
      { phrase: "compared to", weight: 15 },
      { phrase: "instead of", weight: 16 },
      { phrase: "rather than", weight: 14 },
    ],
    switching: [
      { phrase: "switching from", weight: 22 },
      { phrase: "moving away from", weight: 20 },
      { phrase: "leaving", weight: 18 },
      { phrase: "done with", weight: 24 },
    ],
  },
  quality: {
    premium: [
      { phrase: "high quality", weight: 18 },
      { phrase: "professional", weight: 15 },
      { phrase: "top notch", weight: 20 },
      { phrase: "excellent", weight: 16 },
      { phrase: "best", weight: 12 },
      { phrase: "premium", weight: 22 },
    ],
    experience: [
      { phrase: "experienced", weight: 16 },
      { phrase: "expert", weight: 18 },
      { phrase: "skilled", weight: 14 },
      { phrase: "talented", weight: 12 },
      { phrase: "proven", weight: 16 },
      { phrase: "senior", weight: 15 },
    ],
    portfolio: [
      { phrase: "portfolio", weight: 14 },
      { phrase: "examples", weight: 12 },
      { phrase: "previous work", weight: 16 },
      { phrase: "case studies", weight: 18 },
      { phrase: "references", weight: 15 },
    ],
  },
};

module.exports = {
  subredditTiers,
  exclusionPatterns,
  signalPatterns,
};
